apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: hello-world-rs
spec:
    replicas: 3
    selector:
        matchLabels:
            app: hello-world-app
    template:
        metadata:
            labels:
                app: hello-world-app
        spec:
            containers:
                - name: hello-world-rs-con
                  image: elfastahe/hello.world:v2
                  ports:
                      - containerPort: 8080